version: "3"

services:
  python:
    image: app
    container_name: test_app
    ports:
      - "5000:5000"
    logging:
      driver: local

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    logging:
      driver: local

